export const htmlCssBottCampVideoData = [
  "Welcome & Curriculum Overview",
  "Join Our Chat Community",
  "Important Note On Leaving Feedback!",
  "A First Taste of HTML & CSS",
  "How The Web Works",
  "The Roles of HTML, CSS, and JS",
  "Quick Quiz On The Roles of HTML & CSS",
  "Installing The Tools We Need",
  "Configuring VSCode",
  "Important Note On The Course Exercises",
  "Introducing HTML",
  "The Basic HTML Workflow",
  "The Paragraph Element",
  "Mozilla Developer Network",
  "Chrome Developer Tools",
  "Document Structure",
  "Creating HTML Comments",
  "Creating Headings",
  "HTML Basics Exercise",
  "Working With HTML Lists",
  "The Em, Strong, B, and I Elements",
  "Nesting Elements",
  "Superscript and Subscript",
  "Inline Vs. Block Elements",
  "Creating Links",
  "Other Types of Links",
  "Creating Images",
  "Pasta Recipe Exercise",
  "Creating Text Inputs and Buttons",
  "The Form Element",
  "Name and Placeholder Attributes",
  "Properly Labelling Form Controls",
  "Other Types of Inputs",
  "Checkboxes, Textareas, and Range Inputs",
  "Selects and Radio Button Groupings",
  "Course Landing Page Form Exercise",
  "Spans",
  "Divs",
  "Tables",
  "Semantic Markup",
  "Semantic Elements",
  "Getting Our Starter Code",
  "Working Within Inline Styles",
  "Writing Internal Styles",
  "External Styles: The Best Way To Write Styles",
  "Quick Note on Codepen",
  "Anatomy of CSS",
  "The Element Selector",
  "CSS Basics Exercise",
  "Working with background-color",
  "Quick Tip: MDN & Comments",
  "Named Colors",
  "Understanding RGB Colors",
  "Hexadecimal Colors",
  "RGBA Colors and Opacity",
  "Colors Quiz",
  "CSS Inheritance",
  "CSS Colors Exercise",
  "Changing Fonts with Font-Family",
  "Font-size, font-weight, and font-style",
  "Changing Text Alignment",
  "Line-height, letter-spacing, and word-spacing",
  "Adding Custom Fonts With Google Fonts",
  "Styling Text Exercise",
  "Creating Text Shadows",
  "Our First Mini Project: Cantilever",
  "Text-transform & text-decoration",
  "The ID Selector",
  "The Class Selector",
  "Styling Lists",
  "Styling Links and :hover Pseudo-Class",
  "The Font Shorthand Property",
  "Leafy Seadragon Exercise",
  "The Universal Selector",
  "The Attribute Selector",
  "Grouping Selectors",
  "Descendant & Child Combinators",
  "Compound Selectors",
  "CSS Selectors Exercise",
  "Introducing The Box Model",
  "Working With Borders",
  "Width, Height, and Percentages",
  "Adding Padding to Elements",
  "Working With Margins",
  "The Alternate Box Model",
  "The Display Property",
  "Display: None",
  "Negative Margin & Margin Auto",
  "Margin Collapsing: WTF?",
  "A Common Layout Pattern",
  "Min and Max Width",
  "Rounding Elements With Border Radius",
  "Box Shadows",
  "Working With Overflow",
  "Ski Resort Exercise",
  "Introducing Our Project",
  "Basic Project Setup",
  "Writing The Navbar Markup",
  "Styling The Navbar",
  "Finishing Up The Navbar",
  "Creating The Photo Grid",
  "Continuing The Photo Grid",
  "Finishing The Photo Grid",
  "Adding The Footer Content",
  "Section Introduction",
  "The Sibling Combinator",
  "Working With Pseudo-Classes",
  "Styling Pseudo-Elements",
  "CSS Selectors Pt. 2 Exercise",
  "The Basics of Specificity",
  "Inline Styles and Specificity",
  "Calculating Specificity Values",
  "!important and The Cascade",
  "Wrapping Up The Cascade",
  "Cascade & Specificity Quiz",
  "Introducing Our Blog Post Project",
  "Centering The Main Content",
  "Working on Typography",
  "Creating the Headline Section",
  "Implementing Our Headings",
  "Adding In Code Styles",
  "Creating the Footer",
  "Writing The Full Size Hero",
  "Absolute Units: Pixels, Centimeters, and More!",
  "Working With Percentages",
  "The Joy of Rem Units",
  "Understanding The Em Unit",
  "Vw and Vh Units",
  "CSS Units Quiz",
  "Which Units Should You Use?",
  "Working With Floats",
  "Introducing The Project",
  "Setting Up The Navbar",
  "Finishing The Navbar",
  "Starting The Hero Content",
  "Making The Skills Section",
  "Creating The Blog Section",
  "Adding The Events Section",
  "Making A Simple Footer",
  "Working With Background Images",
  "Controlling Background-Repeat",
  "Sizing Our Background",
  "Positioning Background",
  "Working With Background-Clip",
  "Background Exercise",
  "An Important Note About Gradients!",
  "Creating Linear Gradients",
  "Radial, Conic, and Repeating Gradients",
  "The Background Shorthand Property",
  "Fancy CSS Filters",
  "Introducing Positioning",
  "Relative Positioning",
  "Controlling Layers With Z-Index",
  "Absolute Positioning Pt 1",
  "Absolute Positioning Pt 2",
  "Creating A Button Badge",
  "Fixed Positioning",
  "Positioning Exercise #1",
  "Positioning Exercise #2",
  "Positioning Exercise #3",
  "Introducing Transitions",
  "The Basic Transition Syntax",
  "Working With Multiple Transitions",
  "Transition Timing Functions",
  "Transition Delays",
  "Understanding Animation Performance",
  "Introducing Transforms",
  "Other Types of Transformations",
  "Transform Origin",
  "Building Fancy Button Hover Effects",
  "Introducing Flexbox",
  "Display: Flex and Flex Axis",
  "Working With Flex-Direction",
  "Flexbox Exercise 1",
  "Flex-Wrap",
  "Justify-Content",
  "Flexbox Exercise 2",
  "Align-Items",
  "Flexbox Exercise 3",
  "Align-Content",
  "Flexbox Exercise 4",
  "Align-Self",
  "Flexbox Exercise 5",
  "The Flex-Grow Property",
  "Controlling Shrinkage With Flex-Shrink",
  "Flex-Basis: Important & Confusing",
  "The Flex Shorthand Property",
  "The Order Flex-Item Property",
  "Flexbox Patterns: Building A Simple Navbar",
  "Flexbox Patterns: Nested Flex Containers",
  "Flexbox Patterns: Centering Content",
  "Flexbox Patterns: Building A Card Layout",
  "Introducing The Cost Estimator Project",
  "Building Our Container",
  "Creating The Top Tabs",
  "Positioning The Tabs Underline",
  "Creating The Active Tab Styles",
  "Adding The Toggle Section",
  "Building The Sessions Card",
  "Creating The Slider",
  "Creating The Two Price Cards",
  "Finishing Up The Price Cards",
  "Introducing Responsive Design",
  "Our First Media Query",
  "More On Media Queries",
  "Working With Media Features",
  "Media Query Logical Operators",
  "Media Queries Exercise",
  "Media Queries Level 4 & 5",
  "Common Responsive Breakpoints",
  "Creating a Simple Responsive Navbar",
  "Responsive Flexbox Grid Demo",
  "Mobile First vs. Desktop First Design",
  "Building a Simple Mobile-First Layout",
  "Making Cantilever Responsive",
  "Making Potter Portfolio Responsive",
  "Making Hazel CV Project Responsive",
  "Making Cost Estimator Responsive",
  "Introducing CSS Grid",
  "Enabling CSS Grid",
  "Grid-Template-Columns",
  "Grid-Template-Rows",
  "Grid Exercise 1",
  "Grid-Template Shorthand Property",
  "The Minmax() Function",
  "Working With Repeat()",
  "Fit-Content",
  "Controlling Grid Gaps",
  "Grid Exercise 2",
  "Working with Grid Lines",
  "Positioning Grid Items",
  "The Span Keyword",
  "The Grid-Area Shorthand Property",
  "Naming Our Grid Lines",
  "Grid-Template-Areas",
  "Using Grid-Template-Areas With Rows & Cols",
  "Grid-Auto-Flow",
  "Grid Auto Columns & Rows",
  "Autofit and Autofill",
  "Introducing Our Grid Project",
  "Creating Image Overlay Pt 1",
  "Creating Image Overlay Pt 2",
  "Adding In Our Images",
  "Positioning Our Images On The Grid",
  "Making Our Grid Layout Responsive",
  "Fixing Our Image Overlays",
  "Building The Navbar",
  "Finalizing The Navbar and Footer",
  "Creating The Hamburger Button",
  "Introducing Keyframes Animations",
  "Defining @keyframes",
  "More Practice With @Keyframes",
  "Animation Delay, Repeat, and More!",
  "Reusing Animations",
  "Animation Shorthand Property",
  "Building A Simple Spinner Animation",
  "Creating a More Complex Loader",
  "The Animation Fill Mode Property",
  "Introducing Our Animated Drawer",
  "Writing The Individual Bar Animations",
  "A Lightspeed Crash Course In JavaScript",
  "Making Our Hamburger Button Work",
  "Creating The Mobile Drawer Menu",
  "Animating The Drawer Slide-Out",
  "Introducing Before and After",
  "Creating Decorative Quotes With Pseudo-Elements",
  "Gradient Borders With Pseudo-Elements",
  "Fancy Animated Buttons With Pseudo-Elements",
  "Super Fancy Animated Spinner With Pseudo-Elements",
  "Custom Form Controls With Pseudo-Elements",
  "Introducing CSS Variables",
  "Writing CSS Variables",
  "The :root pseudo-class",
  "Variables and Media Queries",
  "Using Variables For Sizes",
  "Introducing Calc()",
  "The Rules of Calc()",
  "Another Example of Using Calc()",
  "Introducing Swipe",
  "Setting Up Our Font Variables",
  "Defining Basic Heading Styles",
  "Writing General Link Styles",
  "Defining Body Styles",
  "Creating our Text Classes - Subtitle, Secondary Text",
  "Defining Our Button Styles - Primary & Secondary Buttons",
  "Creating Our Buttons With Animated Icons",
  "Building The Navbar",
  "Defining Our Two-Column Layout Classes",
  "Writing The Hero Markup",
  "Styling The Page Hero",
  "Building The Partners Grid Section",
  "Adding The Unified Platform Section",
  "Creating Our Graphic Photos Grid",
  "Writing Our Reusable Card Class",
  "Adding The Integrations Section",
  "Defining The Why Swipe Section",
  "Creating The Global Section",
  "Positioning The Globe Image",
  "Adding The Virtual Events Section Markup",
  "Styling The Virtual Events Section",
  "Building The Getting Started Section",
  "Writing The Page Footer Markup",
  "Styling The Page Footer",
  "Adding The First Angled Stripe",
  "Finishing The Angled Stripes",
  "Creating The Animated Gradient Hero Background",
  "Fixing An Issue With Our Angled Stripes",
  "Starting To Make Swipe Responsive",
  "Making The Partners Grid Responsive",
  "Making The Unified Platform Section Responsive",
  "Making The Integrations Section Responsive",
  "Making The Why Swipe Section Responsive",
  "Making The Global Section Responsive",
  "Making The Virtual Events Section Responsive",
  "Making The Bottom of The Page Responsive",
  "Making The Page Hero Responsive",
  "Adding Our Responsive Navbar",
  "Responsive Tweaks To Background Stripes",
  "Cleaning Up Our CSS",
  "Fixing A Minor Issue With Border Radius",
  "Fixing Another Minor Issue With Partners Grid",
];
